@props(['items', 'broker' => false, 'prefix' => 'client'])
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white">
    <div class="hidden overflow-x-auto md:block">
        <table class="w-full text-left text-sm">
            <thead class="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th scope="col" class="px-5 py-4">Claim reference / cover</th>@if($broker)<th scope="col" class="px-5 py-4">Cedant</th>@endif<th scope="col" class="px-5 py-4">Type</th><th scope="col" class="px-5 py-4">Submitted</th><th scope="col" class="px-5 py-4">Status</th>{{-- Portal status deferred; use the mirrored RBS claim status.
<th scope="col" class="px-5 py-4">Status</th>
--}}<th scope="col" class="px-5 py-4"><span class="sr-only">Actions</span></th></tr></thead>
            <tbody class="divide-y divide-slate-100">@forelse($items as $item)<tr class="hover:bg-slate-50/70"><td class="px-5 py-4"><p class="font-semibold text-brand-800">{{ $item['id'] }}</p><p class="mt-1 max-w-xs text-xs text-slate-500">{{ str($item['title'])->limit(100) }}</p></td>@if($broker)<td class="px-5 py-4">{{ $item['company'] }}</td>@endif<td class="px-5 py-4">{{ $item['type'] }}</td><td class="whitespace-nowrap px-5 py-4 text-slate-500">{{ $item['date'] }}</td><td class="px-5 py-4"><span class="inline-block rounded-full bg-brand-50 px-3 py-1.5 text-xs font-medium text-brand-800">{{ $item['status'] ?? 'Not available' }}</span></td>{{-- Portal status deferred; use the mirrored RBS claim status.
<td class="px-5 py-4"><span class="inline-block rounded-full bg-brand-50 px-3 py-1.5 text-xs font-medium text-brand-800">{{ str($item['status'])->replace('_', ' ')->title() }}</span></td>
--}}<td class="px-5 py-4"><a href="{{ route($prefix.'.submissions.show', $item['route_key'] ?? $item['id']) }}" aria-label="View {{ $item['id'] }}" class="inline-block rounded-lg border border-slate-200 px-3 py-2 font-semibold text-brand-700 hover:bg-brand-50">View &rarr;</a></td></tr>@empty<tr><td colspan="{{ $broker ? 6 : 5 }}" class="p-10 text-center text-slate-500">No submissions match your filters.</td></tr>@endforelse</tbody>
        </table>
    </div>
    <div class="divide-y divide-slate-100 md:hidden">@forelse($items as $item)<article class="p-5"><div class="flex items-start justify-between gap-3"><p class="text-xs font-semibold text-brand-700">{{ $item['id'] }}</p><span class="rounded-full bg-brand-50 px-2 py-1 text-xs text-brand-800"><span class="sr-only">Status: </span>{{ $item['status'] ?? 'Not available' }}</span>{{-- Portal status deferred; use the mirrored RBS claim status.
<span class="rounded-full bg-brand-50 px-2 py-1 text-xs text-brand-800">{{ str($item['status'])->replace('_', ' ')->title() }}</span>
--}}</div><h3 class="mt-3 font-semibold">{{ str($item['title'])->limit(100) }}</h3>@if($broker)<p class="mt-2 text-sm text-slate-500">{{ $item['company'] }}</p>@endif<p class="mt-2 text-xs text-slate-500">{{ $item['type'] }} · {{ $item['date'] }}</p><a href="{{ route($prefix.'.submissions.show', $item['route_key'] ?? $item['id']) }}" class="mt-4 inline-block rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-brand-700">View details &rarr;</a></article>@empty<p class="p-6 text-sm text-slate-500">No submissions match your filters.</p>@endforelse</div>
</div>
