<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ProfitCommission extends Model
{
    protected $fillable = [
        'DocNo',
        'RecNo',
        'RskNo',
        'RskDocCode',
        'RskDocDesc',
        'RskDate',
        'RskPerd',
        'RskYear',
        'RskQtr',
        'RskAcctTypeCode',
        'RskAcctTypeDesc',
        'CVNo',
        'CVRef',
        'CVBizTypeCode',
        'CVBizTypeDesc',
        'CVStartDate',
        'CVEndDate',
        'CVYear',
        'CVQtr',
        'CVCusCode',
        'CVCusName',
        'CVCusPostal',
        'CVCusTown',
        'CVCusCtryCode',
        'CVCusCtryDesc',
        'CVCusMktCode',
        'CVCusMktDesc',
        'REDivCode',
        'REDivDesc',
        'RETypeCode',
        'RETypeDesc',
        'REGrpCode',
        'REGrpDesc',
        'RECatCode',
        'RECatDesc',
        'RETreatyTypeCode',
        'RETreatyTypeDesc',
        'REClassCode',
        'REClassDesc',
        'CedCode',
        'CedName',
        'CedPostal',
        'CedTown',
        'CedCtryCode',
        'CedCtryDesc',
        'CedMktCode',
        'CedMktDesc',
        'CedCurnCode',
        'CedCurnDesc',
        'CedAmtFor',
        'CedBrkShr',
        'CedCompShr',
        'CedOptShr',
        'CommOptShr',
        'BrkgOptShr',
        'TotalTax',
        'TotalComm',
        'TotalBrkg',
        'NetAmtCompShr',
        'NetAmtOptShr',
        'NetAmt',
        'MPosted',
        'Comments',
        'CreatedBy',
        'CreatedOn',
        'LastUser',
        'LastMaintained',
        'MExport',
        'MExported',
        'MOperator',
        'AcctCode',
        'AcctName',
        'AcctPostal',
        'AcctTown',
        'AcctMktCode',
        'AcctMktDesc',
        'AcctCurnCode',
        'AcctCurnDesc',
        'LocCurnOper',
        'AcctCtryCode',
        'AcctCtryDesc',
        'RskTypeCode',
        'RskTypeDesc',
        'RiderNo',
        'RiderDesc',
        'ScreenCode',
        'ClaimNo',
        'InterimNo',
        'RiskNoteAmount',
        'AmountDueToRein',
        'BalanceDiff',
        'Balanced',
        'PCPercent',
        'AmountBeforePC',
        'Committed',
        'InstallmentDate',
        'Reversed',
        'ReversalReason',
        'ReversalDoc',
        'NetAmtB',
        'BatchNo',
        'EntryNo',
        'InvoiceAmount',
        'BrokerageEarned',
        'ReinsurerAmount',
        'ReinsurerBrokerage',
        'ReinsurerFullAmount',
        'AmountEntered',
        'last_synced_at',
    ];

    protected function casts(): array
    {
        return [
            'RecNo' => 'integer',
            'CedAmtFor' => 'decimal:8',
            'CedBrkShr' => 'decimal:8',
            'CedCompShr' => 'decimal:8',
            'CedOptShr' => 'decimal:8',
            'CommOptShr' => 'decimal:8',
            'BrkgOptShr' => 'decimal:8',
            'TotalTax' => 'decimal:8',
            'TotalComm' => 'decimal:8',
            'TotalBrkg' => 'decimal:8',
            'NetAmtCompShr' => 'decimal:8',
            'NetAmtOptShr' => 'decimal:8',
            'NetAmt' => 'decimal:8',
            'MPosted' => 'integer',
            'MExport' => 'integer',
            'MExported' => 'integer',
            'MOperator' => 'integer',
            'LocCurnOper' => 'integer',
            'RiskNoteAmount' => 'decimal:8',
            'AmountDueToRein' => 'decimal:8',
            'BalanceDiff' => 'decimal:8',
            'PCPercent' => 'decimal:8',
            'AmountBeforePC' => 'decimal:8',
            'Committed' => 'integer',
            'InstallmentDate' => 'integer',
            'Reversed' => 'integer',
            'NetAmtB' => 'decimal:8',
            'BatchNo' => 'integer',
            'EntryNo' => 'integer',
            'InvoiceAmount' => 'decimal:8',
            'BrokerageEarned' => 'decimal:8',
            'ReinsurerAmount' => 'decimal:8',
            'ReinsurerBrokerage' => 'decimal:8',
            'ReinsurerFullAmount' => 'decimal:8',
            'AmountEntered' => 'decimal:8',
            'last_synced_at' => 'datetime',
        ];
    }

    public function details(): HasMany
    {
        return $this->hasMany(ProfitCommissionDetail::class, 'DocumentNo', 'DocNo');
    }

    public function cover(): BelongsTo
    {
        return $this->belongsTo(Cover::class, 'CVNo', 'CoverNo');
    }

    public function cedant(): BelongsTo
    {
        return $this->belongsTo(Company::class, 'CedCode', 'CmpCode');
    }
}
